### ISSUE TITLE
Use StdLib-Jdk8 everywhere

### ISSUE THREAD

**Issue by jaredsburrows** [JakeWharton/SdkSearch#139]
JDK8 versions of Kotlin libraries are used:
 - JDK8
   - `org.jetbrains.kotlinx:kotlinx-coroutines-jdk8` - from https://github.com/JakeWharton/SdkSearch/blob/master/build.gradle
   - Forcing source and taget to be Java 8 - from https://github.com/JakeWharton/SdkSearch/blob/master/frontend/android/build.gradle
- Non JDK specificed:
   - `org.jetbrains.kotlin:kotlin-stdlib`

We should keep this consistent and use `org.jetbrains.kotlin:kotlin-stdlib-jdk8` instead of `org.jetbrains.kotlin:kotlin-stdlib`.

**Comment by JakeWharton** [comment]
This was intentional as the Android app can't use the extensions provided by the jdk8 variant. So we'd just be adding additional extensions which can't be used to have them removed by R8. The tools which run on the JVM, however, require Java 8 and thus could use the extensions (but I have no idea if they do or not).
